```{r}
library(rsofun)
library(dplyr)
library(readr)
library(lubridate)
source("get_obs_bysite_fluxnet2015.R")
source("train_predict_fvar.R")
source("predict_nn.R")
source("prepare_trainingdata_fvar.R")
source("remove_outliers.R")
```


# Get FLUXNET 2015 data

Read observational data including soil moisture for one site (`"AU-How"`) from a FLUXNET 2015 data file (standard).
```{r}
getvars <- c( 
  "GPP_NT_VUT_REF", 
  "GPP_DT_VUT_REF",                
  "LE_F_MDS", 
  "LE_F_MDS_QC", 
  "NEE_VUT_REF_NIGHT_QC", 
  "NEE_VUT_REF_DAY_QC", # quality flag that goes with GPP 
  "TA_F",
  "VPD_F",
  "P_F",
  "SW_IN_F",
  "NETRAD"
  )
df <- get_obs_bysite_fluxnet2015( sitename="AU-How", path_fluxnet2015="./", timescale="d", getvars=getvars )
```

# Prepare data for training

Prepare training data, removing NAs and outliers.
```{r}
## use all observational soil moisture data
varnams_soilm <- df %>% 
  dplyr::select( starts_with("SWC_") ) %>% 
  dplyr::select( -ends_with("QC") ) %>% 
  names()

## define settings used by multiple functions as a list
settings <- list( 
  varnam_target = "transp_obs", 
  predictors    = c("temp","vpd","swin"), 
  varnams_soilm = varnams_soilm 
  )

df_train <- prepare_trainingdata_fvar( df, settings )
```


# Get soil moisture threshold

```{r eval=FALSE}
profile_soilmthreshold_fvar( df_train, settings )
```

# Train models and predict `fvar`

```{r}
df <- train_predict_fvar( 
  df_train, 
  varnam_target      = settings$varnam_target, 
  varnams_soilm      = settings$varnams_soilm, 
  varnams_predictors = settings$predictors,
  hidden_good        = 10, 
  hidden_all         = 10, 
  soilm_threshold    = 0.6, 
  nrep               = 3, 
  weights            = NA, 
  package            = "nnet" 
  ) %>% 
  right_join( df, by="date" )
```

# Identify soil moisture droughts

```{r}
get_droughts_fvar( df )
```

# Align data by droughts

```{r}
align_by_event( df, "is_drought_byvar" )
```
